package server

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strconv"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/nbaertsch/mythic-sdk-go/pkg/mythic"
	"github.com/nbaertsch/mythic-sdk-go/pkg/mythic/types"
)

// registerTasksTools registers task and response management MCP tools
func (s *Server) registerTasksTools() {
	// Task operations

	// mythic_issue_task - Issue a task to a callback
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_issue_task",
		Description: "Issue a task/command to a callback (agent)",
	}, s.handleIssueTask)

	// mythic_get_task - Get task details
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_task",
		Description: "Get details of a specific task by ID",
	}, s.handleGetTask)

	// mythic_update_task - Update task properties
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_update_task",
		Description: "Update a task's properties (comment, completed, etc.)",
	}, s.handleUpdateTask)

	// mythic_get_callback_tasks - Get tasks for a callback
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_callback_tasks",
		Description: "Get all tasks for a specific callback with optional limit",
	}, s.handleGetCallbackTasks)

	// mythic_get_tasks_by_status - Filter tasks by status
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_tasks_by_status",
		Description: "Get tasks for a callback filtered by status (submitted, processing, completed, error, etc.)",
	}, s.handleGetTasksByStatus)

	// mythic_wait_for_task - Wait for task completion
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_wait_for_task",
		Description: "Wait for a task to complete with timeout",
	}, s.handleWaitForTask)

	// mythic_get_task_output - Get task output/responses
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_task_output",
		Description: "Get the output/responses for a task",
	}, s.handleGetTaskOutput)

	// mythic_reissue_task - Reissue a task
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_reissue_task",
		Description: "[UNSUPPORTED] Reissue a task with the same parameters. " +
			"NOTE: The Mythic server has this mutation in its GraphQL schema but returns " +
			"'Function not implemented' at runtime. This tool is non-functional until Mythic implements it server-side.",
	}, s.handleReissueTask)

	// mythic_reissue_task_with_handler - Reissue task with handler
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_reissue_task_with_handler",
		Description: "[UNSUPPORTED] Reissue a task with handler for callback structure updates. " +
			"NOTE: The Mythic server has this mutation in its GraphQL schema but returns " +
			"'Function not implemented' at runtime. This tool is non-functional until Mythic implements it server-side.",
	}, s.handleReissueTaskWithHandler)

	// mythic_get_task_artifacts - Get task artifacts
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_task_artifacts",
		Description: "Get artifacts (IOCs) generated by a task",
	}, s.handleGetTaskArtifacts)

	// mythic_request_opsec_bypass - Request OPSEC bypass
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_request_opsec_bypass",
		Description: "Request bypass for OPSEC checks on a blocked task",
	}, s.handleRequestOpsecBypass)

	// mythic_add_mitre_attack_to_task - Add MITRE ATT&CK mapping
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_add_mitre_attack_to_task",
		Description: "Add MITRE ATT&CK technique mapping to a task",
	}, s.handleAddMitreAttackToTask)

	// Response operations

	// mythic_get_task_responses - Get responses for a task
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_task_responses",
		Description: "Get all responses for a specific task",
	}, s.handleGetTaskResponses)

	// mythic_get_callback_responses - Get responses for a callback
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_callback_responses",
		Description: "Get responses for a callback with optional limit",
	}, s.handleGetCallbackResponses)

	// mythic_get_response - Get specific response
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_response",
		Description: "Get details of a specific response by ID",
	}, s.handleGetResponse)

	// mythic_get_latest_responses - Get latest responses
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_latest_responses",
		Description: "Get the latest responses for an operation",
	}, s.handleGetLatestResponses)

	// mythic_search_responses - Search response text
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_search_responses",
		Description: "Search for responses containing specific text",
	}, s.handleSearchResponses)

	// mythic_get_response_statistics - Get response statistics
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_response_statistics",
		Description: "Get statistics about responses for a specific task",
	}, s.handleGetResponseStatistics)
}

// Tool argument types for task tools

type issueTaskArgs struct {
	CallbackID int    `json:"callback_id" jsonschema:"Display ID of the callback to task"`
	Command    string `json:"command" jsonschema:"Command name to execute"`
	Params     string `json:"params" jsonschema:"Command parameters. Accepts JSON objects (recommended for multi-parameter commands) or plain strings. JSON example: {\"target\": \"127.0.0.1\", \"tcp_port\": 4444}. Plain string example: 'whoami' or 'ls -la /tmp'. Use JSON for commands with multiple/optional/typed parameters to avoid ambiguity. Use plain strings for simple single-value parameters (shell, mkdir, kill). Leave empty for commands with no parameters (pwd, ps, ifconfig, etc.)"`
}

type getTaskArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task"`
}

type updateTaskArgs struct {
	TaskID  int                    `json:"task_id" jsonschema:"Display ID of the task to update"`
	Updates map[string]interface{} `json:"updates" jsonschema:"Map of fields to update (comment, completed, etc.)"`
}

type getCallbackTasksArgs struct {
	CallbackID int `json:"callback_id" jsonschema:"Display ID of the callback"`
	Limit      int `json:"limit,omitempty" jsonschema:"Maximum number of tasks to return (default 100)"`
}

type getTasksByStatusArgs struct {
	CallbackID int    `json:"callback_id" jsonschema:"Display ID of the callback"`
	Status     string `json:"status" jsonschema:"Task status to filter by (submitted, processing, completed, error, etc.)"`
	Limit      int    `json:"limit,omitempty" jsonschema:"Maximum number of tasks to return (default 100)"`
}

type waitForTaskArgs struct {
	TaskID  int `json:"task_id" jsonschema:"Display ID of the task to wait for"`
	Timeout int `json:"timeout,omitempty" jsonschema:"Timeout in seconds (default 60)"`
}

type getTaskOutputArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task"`
}

type reissueTaskArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task to reissue"`
}

type getTaskArtifactsArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task"`
}

type requestOpsecBypassArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task"`
}

type addMitreAttackToTaskArgs struct {
	TaskID      int    `json:"task_id" jsonschema:"Display ID of the task (the number shown in the Mythic UI)"`
	TechniqueID string `json:"technique_id" jsonschema:"MITRE ATT&CK technique ID (e.g., T1055)"`
}

type getTaskResponsesArgs struct {
	TaskID int `json:"task_id" jsonschema:"Display ID of the task"`
}

type getCallbackResponsesArgs struct {
	CallbackID int `json:"callback_id" jsonschema:"Display ID of the callback"`
	Limit      int `json:"limit,omitempty" jsonschema:"Maximum number of responses to return (default 100)"`
}

type getResponseArgs struct {
	ResponseID int `json:"response_id" jsonschema:"ID of the response"`
}

type getLatestResponsesArgs struct {
	OperationID int `json:"operation_id" jsonschema:"ID of the operation"`
	Limit       int `json:"limit,omitempty" jsonschema:"Maximum number of responses to return (default 50)"`
}

type searchResponsesArgs struct {
	SearchTerm string `json:"search_term" jsonschema:"Text to search for in response output"`
	Limit      int    `json:"limit,omitempty" jsonschema:"Maximum number of responses to return (default 50)"`
}

type getResponseStatisticsArgs struct {
	TaskID int `json:"task_id" jsonschema:"Task ID to get statistics for"`
}

// Tool handlers for task operations

// normalizeParams detects if a params string is a JSON object and extracts the value(s).
// LLM agents frequently ignore instructions and pass {"path": "/tmp/foo"} instead of "/tmp/foo".
// This function handles the conversion so Mythic receives the plain string the agent expects.
func normalizeParams(params string) string {
	if params == "" {
		return params
	}

	// Try to parse as JSON object
	var obj map[string]interface{}
	if err := json.Unmarshal([]byte(params), &obj); err != nil {
		// Not JSON — already a plain string, use as-is
		return params
	}

	// Single-key JSON object: extract the value directly
	// e.g. {"path": "/tmp/foo"} → "/tmp/foo"
	if len(obj) == 1 {
		for _, v := range obj {
			switch val := v.(type) {
			case string:
				return val
			case float64:
				// JSON numbers — format as integer if whole
				if val == float64(int(val)) {
					return fmt.Sprintf("%d", int(val))
				}
				return fmt.Sprintf("%g", val)
			default:
				// Complex value — re-serialize
				b, _ := json.Marshal(val)
				return string(b)
			}
		}
	}

	// Multi-key JSON object: pass through as JSON string
	// Mythic will parse it as structured parameters
	return params
}

// handleIssueTask issues a task to a callback
func (s *Server) handleIssueTask(ctx context.Context, req *mcp.CallToolRequest, args issueTaskArgs) (*mcp.CallToolResult, any, error) {
	callbackID := args.CallbackID

	// Smart parameter resolution: handles both plain strings and JSON objects,
	// and auto-converts space-separated strings into structured JSON for
	// multi-argument commands by looking up the command's parameter schema.
	params := s.resolveTaskParams(ctx, callbackID, args.Command, args.Params)

	issueReq := &mythic.TaskRequest{
		CallbackID: &callbackID,
		Command:    args.Command,
		Params:     params,
	}

	task, err := s.mythicClient.IssueTask(ctx, issueReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(task, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Successfully issued task %d to callback %d\nCommand: %s\nStatus: %s\n\n%s",
					task.DisplayID, args.CallbackID, args.Command, task.Status, string(data)),
			},
		},
	}, task, nil
}

// resolveTaskParams handles smart parameter parsing for task commands.
//
// The logic is:
//  1. Empty params → pass through
//  2. Params is valid JSON object/array → pass through (the SDK and Mythic handle it)
//  3. Params is a plain string:
//     a. Look up the command schema from Mythic
//     b. If it's a raw-string command (e.g. shell, run) → pass the string as-is
//     c. If the command has structured parameters → split the string positionally
//     and map values to named parameters with type coercion
//     d. If schema lookup fails → fall back to normalizeParams (Issue #6 compat)
func (s *Server) resolveTaskParams(ctx context.Context, callbackID int, command, params string) string {
	if len(params) == 0 {
		return params
	}

	trimmed := strings.TrimSpace(params)

	// Already valid JSON → pass through directly (don't unwrap structured params)
	if len(trimmed) > 0 && (trimmed[0] == '{' || trimmed[0] == '[') && json.Valid([]byte(trimmed)) {
		return params
	}

	// Plain string input — try to look up the command schema
	callback, err := s.mythicClient.GetCallbackByID(ctx, callbackID)
	if err != nil {
		log.Printf("[resolveTaskParams] failed to get callback %d: %v (falling back to normalizeParams)", callbackID, err)
		return normalizeParams(params)
	}

	cmdWithParams, err := s.mythicClient.GetCommandWithParameters(ctx, callback.PayloadTypeID, command)
	if err != nil {
		log.Printf("[resolveTaskParams] failed to get command schema for %q: %v (falling back to normalizeParams)", command, err)
		return normalizeParams(params)
	}

	// Raw-string commands take the string as-is
	if cmdWithParams.IsRawStringCommand() {
		return params
	}

	// No parameters defined — pass through
	if len(cmdWithParams.Parameters) == 0 {
		return params
	}

	// Parse space-separated values into structured JSON
	structured, err := parsePositionalParams(trimmed, cmdWithParams.Parameters)
	if err != nil {
		log.Printf("[resolveTaskParams] positional parse failed for %q %q: %v (passing as-is)", command, params, err)
		return params
	}

	jsonBytes, err := json.Marshal(structured)
	if err != nil {
		log.Printf("[resolveTaskParams] JSON marshal failed: %v (passing as-is)", err)
		return params
	}

	log.Printf("[resolveTaskParams] parsed %q params: %q -> %s", command, params, string(jsonBytes))
	return string(jsonBytes)
}

// parsePositionalParams maps space-separated values to named command parameters.
// Parameters are filled in order: required parameters first (preserving their
// original order), then optional parameters. Type coercion is applied based on
// the parameter's declared type.
func parsePositionalParams(input string, parameters []*types.CommandParameter) (map[string]interface{}, error) {
	parts := strings.Fields(input)
	if len(parts) == 0 {
		return nil, fmt.Errorf("empty input")
	}

	// Build ordered list: required params first, then optional
	var required []*types.CommandParameter
	var optional []*types.CommandParameter
	for _, p := range parameters {
		if p.Required {
			required = append(required, p)
		} else {
			optional = append(optional, p)
		}
	}
	ordered := append(required, optional...)

	result := make(map[string]interface{})

	for i, part := range parts {
		if i >= len(ordered) {
			// More values than parameters — join remainder into the last param
			lastParam := ordered[len(ordered)-1]
			if existingStr, ok := result[lastParam.Name].(string); ok {
				result[lastParam.Name] = existingStr + " " + strings.Join(parts[i:], " ")
			} else {
				result[lastParam.Name] = strings.Join(parts[i:], " ")
			}
			break
		}

		param := ordered[i]
		val, err := coerceValue(part, param.Type)
		if err != nil {
			return nil, fmt.Errorf("parameter %q: %w", param.Name, err)
		}
		result[param.Name] = val
	}

	return result, nil
}

// coerceValue converts a string value to the appropriate Go type based on
// the Mythic command parameter type.
func coerceValue(value, paramType string) (interface{}, error) {
	switch paramType {
	case types.ParameterTypeNumber:
		if i, err := strconv.ParseInt(value, 10, 64); err == nil {
			return i, nil
		}
		if f, err := strconv.ParseFloat(value, 64); err == nil {
			return f, nil
		}
		return nil, fmt.Errorf("cannot parse %q as number", value)
	case types.ParameterTypeBoolean:
		b, err := strconv.ParseBool(value)
		if err != nil {
			return nil, fmt.Errorf("cannot parse %q as boolean", value)
		}
		return b, nil
	case types.ParameterTypeString, types.ParameterTypeChooseOne:
		return value, nil
	default:
		// Complex types (Array, File, Credential, LinkInfo, etc.) — pass as string
		return value, nil
	}
}

// handleGetTask retrieves a specific task by ID
func (s *Server) handleGetTask(ctx context.Context, req *mcp.CallToolRequest, args getTaskArgs) (*mcp.CallToolResult, any, error) {
	task, err := s.mythicClient.GetTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(task, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Task %d (status: %s)\nCommand: %s\nCallback: %d\n\n%s",
					task.DisplayID, task.Status, task.CommandName, task.CallbackID, string(data)),
			},
		},
	}, task, nil
}

// handleUpdateTask updates a task's properties
func (s *Server) handleUpdateTask(ctx context.Context, req *mcp.CallToolRequest, args updateTaskArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.UpdateTask(ctx, args.TaskID, args.Updates)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully updated task %d", args.TaskID),
				},
			},
		}, map[string]interface{}{
			"task_id": args.TaskID,
			"success": true,
		}, nil
}

// handleGetCallbackTasks retrieves tasks for a callback
func (s *Server) handleGetCallbackTasks(ctx context.Context, req *mcp.CallToolRequest, args getCallbackTasksArgs) (*mcp.CallToolResult, any, error) {
	limit := args.Limit
	if limit == 0 {
		limit = 100
	}

	tasks, err := s.mythicClient.GetTasksForCallback(ctx, args.CallbackID, limit)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(tasks, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Tasks for callback %d (%d total, limit %d):\n\n%s",
					args.CallbackID, len(tasks), limit, string(data)),
			},
		},
	}, wrapList(tasks), nil
}

// handleGetTasksByStatus retrieves tasks filtered by status
func (s *Server) handleGetTasksByStatus(ctx context.Context, req *mcp.CallToolRequest, args getTasksByStatusArgs) (*mcp.CallToolResult, any, error) {
	limit := args.Limit
	if limit == 0 {
		limit = 100
	}

	// Convert string status to TaskStatus type
	status := mythic.TaskStatus(args.Status)

	tasks, err := s.mythicClient.GetTasksByStatus(ctx, args.CallbackID, status, limit)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(tasks, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Tasks with status '%s' for callback %d (%d total, limit %d):\n\n%s",
					args.Status, args.CallbackID, len(tasks), limit, string(data)),
			},
		},
	}, wrapList(tasks), nil
}

// handleWaitForTask waits for a task to complete
func (s *Server) handleWaitForTask(ctx context.Context, req *mcp.CallToolRequest, args waitForTaskArgs) (*mcp.CallToolResult, any, error) {
	timeout := args.Timeout
	if timeout == 0 {
		timeout = 60
	}

	err := s.mythicClient.WaitForTaskComplete(ctx, args.TaskID, timeout)
	if err != nil {
		return nil, nil, translateError(err)
	}

	// Get the task details after completion
	task, err := s.mythicClient.GetTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(task, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Task %d completed with status: %s\n\n%s",
					task.DisplayID, task.Status, string(data)),
			},
		},
	}, task, nil
}

// handleGetTaskOutput retrieves task output/responses
func (s *Server) handleGetTaskOutput(ctx context.Context, req *mcp.CallToolRequest, args getTaskOutputArgs) (*mcp.CallToolResult, any, error) {
	output, err := s.mythicClient.GetTaskOutput(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Output for task %d (%d responses):\n\n%s", args.TaskID, len(output), string(data)),
			},
		},
	}, wrapList(output), nil
}

// handleReissueTask reissues a task
func (s *Server) handleReissueTask(ctx context.Context, req *mcp.CallToolRequest, args reissueTaskArgs) (*mcp.CallToolResult, any, error) {
	newTask, err := s.mythicClient.ReissueTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(newTask, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully reissued task %d as new task %d (%s %s)\n\n%s", args.TaskID, newTask.DisplayID, newTask.CommandName, newTask.Params, string(data)),
				},
			},
		}, newTask, nil
}

// handleReissueTaskWithHandler reissues a task with handler
func (s *Server) handleReissueTaskWithHandler(ctx context.Context, req *mcp.CallToolRequest, args reissueTaskArgs) (*mcp.CallToolResult, any, error) {
	newTask, err := s.mythicClient.ReissueTaskWithHandler(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(newTask, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully reissued task %d with handler as new task %d (%s %s)\n\n%s", args.TaskID, newTask.DisplayID, newTask.CommandName, newTask.Params, string(data)),
				},
			},
		}, newTask, nil
}

// handleGetTaskArtifacts retrieves artifacts for a task
func (s *Server) handleGetTaskArtifacts(ctx context.Context, req *mcp.CallToolRequest, args getTaskArtifactsArgs) (*mcp.CallToolResult, any, error) {
	artifacts, err := s.mythicClient.GetTaskArtifacts(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(artifacts, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Artifacts for task %d (%d total):\n\n%s",
					args.TaskID, len(artifacts), string(data)),
			},
		},
	}, wrapList(artifacts), nil
}

// handleRequestOpsecBypass requests OPSEC bypass for a task
func (s *Server) handleRequestOpsecBypass(ctx context.Context, req *mcp.CallToolRequest, args requestOpsecBypassArgs) (*mcp.CallToolResult, any, error) {
	// Get task first to get its internal ID
	task, err := s.mythicClient.GetTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	err = s.mythicClient.RequestOpsecBypass(ctx, task.ID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully requested OPSEC bypass for task %d", args.TaskID),
				},
			},
		}, map[string]interface{}{
			"task_id": args.TaskID,
			"success": true,
		}, nil
}

// handleAddMitreAttackToTask adds MITRE ATT&CK mapping to a task
func (s *Server) handleAddMitreAttackToTask(ctx context.Context, req *mcp.CallToolRequest, args addMitreAttackToTaskArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.AddMITREAttackToTask(ctx, args.TaskID, args.TechniqueID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully added MITRE ATT&CK technique %s to task %d",
						args.TechniqueID, args.TaskID),
				},
			},
		}, map[string]interface{}{
			"task_id":      args.TaskID,
			"technique_id": args.TechniqueID,
			"success":      true,
		}, nil
}

// Tool handlers for response operations

// handleGetTaskResponses retrieves responses for a task
func (s *Server) handleGetTaskResponses(ctx context.Context, req *mcp.CallToolRequest, args getTaskResponsesArgs) (*mcp.CallToolResult, any, error) {
	// Get task first to get its internal ID
	task, err := s.mythicClient.GetTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	responses, err := s.mythicClient.GetResponsesByTask(ctx, task.ID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(responses, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Responses for task %d (%d total):\n\n%s",
					args.TaskID, len(responses), string(data)),
			},
		},
	}, wrapList(responses), nil
}

// handleGetCallbackResponses retrieves responses for a callback
func (s *Server) handleGetCallbackResponses(ctx context.Context, req *mcp.CallToolRequest, args getCallbackResponsesArgs) (*mcp.CallToolResult, any, error) {
	limit := args.Limit
	if limit == 0 {
		limit = 100
	}

	// Get callback first to get its internal ID
	callback, err := s.mythicClient.GetCallbackByID(ctx, args.CallbackID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	responses, err := s.mythicClient.GetResponsesByCallback(ctx, callback.ID, limit)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(responses, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Responses for callback %d (%d total, limit %d):\n\n%s",
					args.CallbackID, len(responses), limit, string(data)),
			},
		},
	}, wrapList(responses), nil
}

// handleGetResponse retrieves a specific response by ID
func (s *Server) handleGetResponse(ctx context.Context, req *mcp.CallToolRequest, args getResponseArgs) (*mcp.CallToolResult, any, error) {
	response, err := s.mythicClient.GetResponseByID(ctx, args.ResponseID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(response, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Response %d (task %d):\n\n%s",
					response.ID, response.TaskID, string(data)),
			},
		},
	}, response, nil
}

// handleGetLatestResponses retrieves latest responses for an operation
func (s *Server) handleGetLatestResponses(ctx context.Context, req *mcp.CallToolRequest, args getLatestResponsesArgs) (*mcp.CallToolResult, any, error) {
	limit := args.Limit
	if limit == 0 {
		limit = 50
	}

	responses, err := s.mythicClient.GetLatestResponses(ctx, args.OperationID, limit)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(responses, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Latest responses for operation %d (%d total, limit %d):\n\n%s",
					args.OperationID, len(responses), limit, string(data)),
			},
		},
	}, wrapList(responses), nil
}

// handleSearchResponses searches response text
func (s *Server) handleSearchResponses(ctx context.Context, req *mcp.CallToolRequest, args searchResponsesArgs) (*mcp.CallToolResult, any, error) {
	limit := args.Limit
	if limit == 0 {
		limit = 50
	}

	searchReq := &types.ResponseSearchRequest{
		Query: args.SearchTerm,
	}

	responses, err := s.mythicClient.SearchResponses(ctx, searchReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	// Apply limit manually since SDK doesn't support it in SearchResponses
	if len(responses) > limit {
		responses = responses[:limit]
	}

	data, err := json.MarshalIndent(responses, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Search results for '%s' (%d total, limit %d):\n\n%s",
					args.SearchTerm, len(responses), limit, string(data)),
			},
		},
	}, wrapList(responses), nil
}

// handleGetResponseStatistics retrieves response statistics
func (s *Server) handleGetResponseStatistics(ctx context.Context, req *mcp.CallToolRequest, args getResponseStatisticsArgs) (*mcp.CallToolResult, any, error) {
	// Get task first to get its internal ID
	task, err := s.mythicClient.GetTask(ctx, args.TaskID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	stats, err := s.mythicClient.GetResponseStatistics(ctx, task.ID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(stats, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Response statistics for task %d:\n\n%s", args.TaskID, string(data)),
			},
		},
	}, stats, nil
}
