package server

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/nbaertsch/mythic-sdk-go/pkg/mythic/types"
)

// registerC2ProfilesTools registers C2 profile management MCP tools
func (s *Server) registerC2ProfilesTools() {
	// mythic_get_c2_profiles - List all C2 profiles
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_get_c2_profiles",
		Description: "List all installed C2 communication profiles (e.g. http, httpx, smb, tcp). " +
			"Each profile acts as a listener/handler for agent callbacks. " +
			"IMPORTANT: A C2 profile must be STARTED (running=true) before payloads using it can callback. " +
			"Not all agents support all C2 profiles — check the 'supported_agents' field. " +
			"Typical workflow: 1) list profiles, 2) start the profile, 3) get profile parameters, 4) create payload with those parameters.",
	}, s.handleGetC2Profiles)

	// mythic_get_c2_profile - Get specific C2 profile with configuration
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_get_c2_profile",
		Description: "Get details of a specific C2 profile by ID, including its current configuration " +
			"parameter values (callback_host, callback_port, etc.) and whether it is currently running.",
	}, s.handleGetC2Profile)

	// mythic_create_c2_instance - Create a C2 profile instance
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_create_c2_instance",
		Description: "Create a named C2 profile configuration instance. Note: most users do NOT need this — " +
			"C2 profiles are already installed and just need to be STARTED with mythic_start_c2_profile. " +
			"Only use this to create additional named configurations of an existing profile.",
	}, s.handleCreateC2Instance)

	// mythic_import_c2_instance - Import C2 instance configuration
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_import_c2_instance",
		Description: "Import a C2 profile instance from configuration JSON",
	}, s.handleImportC2Instance)

	// mythic_start_c2_profile - Start a C2 profile (listener)
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_start_c2_profile",
		Description: "Start a C2 profile, which begins listening for agent callbacks. " +
			"This is REQUIRED before deploying any payload — without a running C2 profile, agents cannot call back. " +
			"Use mythic_get_c2_profiles first to find the profile ID and check if it is already running.",
	}, s.handleStartC2Profile)

	// mythic_stop_c2_profile - Stop a C2 profile (listener)
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_stop_c2_profile",
		Description: "Stop a running C2 profile listener. WARNING: This will prevent any agents using this profile from calling back.",
	}, s.handleStopC2Profile)

	// mythic_get_c2_profile_output - Get C2 profile output
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_c2_profile_output",
		Description: "Get the stdout/stderr output from a C2 profile instance",
	}, s.handleGetC2ProfileOutput)

	// mythic_c2_host_file - Host a file on C2 profile
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_c2_host_file",
		Description: "Host a file on a C2 profile for agent download. " +
			"Requires the C2 profile ID (from mythic_get_c2_profiles), the file UUID, " +
			"and the URL path where the file will be served.",
	}, s.handleC2HostFile)

	// mythic_c2_sample_message - Get sample C2 message
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_c2_sample_message",
		Description: "Get a sample C2 message for a specific message type",
	}, s.handleC2SampleMessage)

	// mythic_c2_get_ioc - Get IOCs from C2 profile
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_c2_get_ioc",
		Description: "Get indicators of compromise (IOCs) generated by a C2 profile",
	}, s.handleC2GetIOC)
}

// Tool argument types for C2 profile tools

type getC2ProfilesArgs struct{}

type getC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

type createC2InstanceArgs struct {
	C2ProfileID  int    `json:"c2profile_id" jsonschema:"ID of the C2 profile to create an instance of"`
	InstanceName string `json:"instance_name" jsonschema:"Name for this C2 profile instance"`
	C2Instance   string `json:"c2_instance" jsonschema:"JSON string of the instance configuration"`
}

type importC2InstanceArgs struct {
	C2ProfileName string `json:"c2profile_name" jsonschema:"Name of the C2 profile type (e.g. http, httpx)"`
	InstanceName  string `json:"instance_name" jsonschema:"Name for this imported C2 instance"`
	C2Instance    string `json:"c2_instance" jsonschema:"JSON string of the instance configuration"`
}

type startC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile to start"`
}

type stopC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile to stop"`
}

type getC2ProfileOutputArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

type c2HostFileArgs struct {
	ProfileID int    `json:"profile_id" jsonschema:"ID of the C2 profile"`
	FileUUID  string `json:"file_uuid" jsonschema:"UUID of the file to host"`
	HostURL   string `json:"host_url" jsonschema:"URL path where the file will be hosted (e.g. /download/file.exe)"`
}

type c2SampleMessageArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

type c2GetIOCArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

// Tool handlers

// handleGetC2Profiles retrieves all C2 profiles
func (s *Server) handleGetC2Profiles(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfilesArgs) (*mcp.CallToolResult, any, error) {
	profiles, err := s.mythicClient.GetC2Profiles(ctx)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(profiles, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("All C2 profiles (%d total):\n\n%s", len(profiles), string(data)),
			},
		},
	}, wrapList(profiles), nil
}

// handleGetC2Profile retrieves a specific C2 profile by ID, including its
// current configuration parameter values.
func (s *Server) handleGetC2Profile(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	profile, err := s.mythicClient.GetC2ProfileByID(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	// Fetch configuration parameters and populate the profile's Parameters map
	params, paramErr := s.mythicClient.GetC2ProfileParameters(ctx, args.ProfileID)
	if paramErr == nil && len(params) > 0 {
		configuration := make(map[string]interface{}, len(params))
		for _, p := range params {
			configuration[p.Name] = map[string]interface{}{
				"value":          p.DefaultValue,
				"type":           p.ParameterType,
				"required":       p.Required,
				"description":    p.Description,
				"verifier_regex": p.VerifierRegex,
			}
			// Include choices for selection types
			if p.Choices != "" && p.Choices != "[]" {
				configuration[p.Name].(map[string]interface{})["choices"] = p.Choices
			}
		}
		profile.Parameters = configuration
	}

	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	status := "Stopped"
	if profile.Running {
		status = "Running"
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("C2 Profile %d (%s): %s\nType: %s\n\n%s",
					profile.ID, status, profile.Name, profile.Description, string(data)),
			},
		},
	}, profile, nil
}

// handleCreateC2Instance creates a new C2 profile instance
func (s *Server) handleCreateC2Instance(ctx context.Context, req *mcp.CallToolRequest, args createC2InstanceArgs) (*mcp.CallToolResult, any, error) {
	createReq := &types.CreateC2InstanceRequest{
		C2ProfileID:  args.C2ProfileID,
		InstanceName: args.InstanceName,
		C2Instance:   args.C2Instance,
	}

	err := s.mythicClient.CreateC2Instance(ctx, createReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Successfully created C2 instance '%s' for profile ID %d",
					args.InstanceName, args.C2ProfileID),
			},
		},
	}, map[string]interface{}{
		"instance_name": args.InstanceName,
		"c2profile_id":  args.C2ProfileID,
		"success":       true,
	}, nil
}

// handleImportC2Instance imports a C2 instance from configuration
func (s *Server) handleImportC2Instance(ctx context.Context, req *mcp.CallToolRequest, args importC2InstanceArgs) (*mcp.CallToolResult, any, error) {
	importReq := &types.ImportC2InstanceRequest{
		C2ProfileName: args.C2ProfileName,
		InstanceName:  args.InstanceName,
		C2Instance:    args.C2Instance,
	}

	err := s.mythicClient.ImportC2Instance(ctx, importReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Successfully imported C2 instance '%s' for profile '%s'",
					args.InstanceName, args.C2ProfileName),
			},
		},
	}, map[string]interface{}{
		"instance_name":  args.InstanceName,
		"c2profile_name": args.C2ProfileName,
		"success":        true,
	}, nil
}

// handleStartC2Profile starts a C2 profile
func (s *Server) handleStartC2Profile(ctx context.Context, req *mcp.CallToolRequest, args startC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.StartStopProfile(ctx, args.ProfileID, true)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully started C2 profile %d", args.ProfileID),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"action":     "start",
			"success":    true,
		}, nil
}

// handleStopC2Profile stops a C2 profile
func (s *Server) handleStopC2Profile(ctx context.Context, req *mcp.CallToolRequest, args stopC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.StartStopProfile(ctx, args.ProfileID, false)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully stopped C2 profile %d", args.ProfileID),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"action":     "stop",
			"success":    true,
		}, nil
}

// handleGetC2ProfileOutput retrieves C2 profile output
func (s *Server) handleGetC2ProfileOutput(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfileOutputArgs) (*mcp.CallToolResult, any, error) {
	output, err := s.mythicClient.GetProfileOutput(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Output for C2 profile %d:\n\n%s", args.ProfileID, string(data)),
			},
		},
	}, output, nil
}

// handleC2HostFile hosts a file on a C2 profile
func (s *Server) handleC2HostFile(ctx context.Context, req *mcp.CallToolRequest, args c2HostFileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.C2HostFile(ctx, args.ProfileID, args.FileUUID, args.HostURL)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully hosted file %s on C2 profile %d at %s", args.FileUUID, args.ProfileID, args.HostURL),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"file_uuid":  args.FileUUID,
			"host_url":   args.HostURL,
			"success":    true,
		}, nil
}

// handleC2SampleMessage retrieves a sample C2 message
func (s *Server) handleC2SampleMessage(ctx context.Context, req *mcp.CallToolRequest, args c2SampleMessageArgs) (*mcp.CallToolResult, any, error) {
	// Resolve profile ID to profile name (Mythic API uses name as "uuid")
	profile, err := s.mythicClient.GetC2ProfileByID(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	message, err := s.mythicClient.C2SampleMessage(ctx, profile.Name)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(message, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Sample message for C2 profile '%s' (ID: %d):\n\n%s",
					profile.Name, args.ProfileID, string(data)),
			},
		},
	}, message, nil
}

// handleC2GetIOC retrieves IOCs from a C2 profile
func (s *Server) handleC2GetIOC(ctx context.Context, req *mcp.CallToolRequest, args c2GetIOCArgs) (*mcp.CallToolResult, any, error) {
	// Resolve profile ID to profile name (Mythic API uses name as "uuid")
	profile, err := s.mythicClient.GetC2ProfileByID(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	ioc, err := s.mythicClient.C2GetIOC(ctx, profile.Name)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(ioc, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("IOCs for C2 profile '%s' (ID: %d):\n\n%s", profile.Name, args.ProfileID, string(data)),
			},
		},
	}, ioc, nil
}
