package server

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/nbaertsch/mythic-sdk-go/pkg/mythic/types"
)

// registerC2ProfilesTools registers C2 profile management MCP tools
func (s *Server) registerC2ProfilesTools() {
	// mythic_get_c2_profiles - List all C2 profiles
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_get_c2_profiles",
		Description: "List all installed C2 communication profiles (e.g. http, httpx, smb, tcp). " +
			"In Mythic, each C2 profile IS the listener — there is no separate listener concept. " +
			"When running=true the profile is actively listening for agent callbacks. " +
			"Not all agents support all profiles (e.g. Poseidon uses 'http', Xenon uses 'httpx'). " +
			"Workflow: 1) list profiles, 2) ensure the needed profile is running, 3) get its parameters, 4) create a payload with those parameters.",
	}, s.handleGetC2Profiles)

	// mythic_get_c2_profile - Get specific C2 profile
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_c2_profile",
		Description: "Get details of a specific C2 profile by ID, including whether it is currently running (actively listening for callbacks).",
	}, s.handleGetC2Profile)

	// mythic_create_c2_instance - Save a named C2 parameter config (rarely needed)
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_create_c2_instance",
		Description: "Save a named set of C2 profile parameters as a reusable template. " +
			"Most users do NOT need this — C2 profiles are already installed and just need to be started. " +
			"To use a C2 profile with a payload, pass parameters directly in mythic_create_payload's c2_profiles field.",
	}, s.handleCreateC2Instance)

	// mythic_import_c2_instance - Import C2 instance configuration
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_import_c2_instance",
		Description: "Import a C2 profile instance from configuration JSON",
	}, s.handleImportC2Instance)

	// mythic_start_c2_profile - Start a C2 profile (begin listening)
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_start_c2_profile",
		Description: "Start a C2 profile so it begins listening for agent callbacks. " +
			"A profile must be running before deployed payloads can call back. " +
			"Use mythic_get_c2_profiles first to check if it is already running.",
	}, s.handleStartC2Profile)

	// mythic_stop_c2_profile - Stop a C2 profile (stop listening)
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name: "mythic_stop_c2_profile",
		Description: "Stop a running C2 profile so it no longer listens for callbacks. " +
			"WARNING: any agents using this profile will lose their ability to call back until it is restarted.",
	}, s.handleStopC2Profile)

	// mythic_get_c2_profile_output - Get C2 profile output
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_get_c2_profile_output",
		Description: "Get the stdout/stderr output from a C2 profile instance",
	}, s.handleGetC2ProfileOutput)

	// mythic_c2_host_file - Host a file on C2 profile
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_c2_host_file",
		Description: "Host a file on a C2 profile for agent download",
	}, s.handleC2HostFile)

	// mythic_c2_sample_message - Get sample C2 message
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_c2_sample_message",
		Description: "Get a sample C2 message for a specific message type",
	}, s.handleC2SampleMessage)

	// mythic_c2_get_ioc - Get IOCs from C2 profile
	mcp.AddTool(s.mcpServer, &mcp.Tool{
		Name:        "mythic_c2_get_ioc",
		Description: "Get indicators of compromise (IOCs) generated by a C2 profile",
	}, s.handleC2GetIOC)
}

// Tool argument types for C2 profile tools

type getC2ProfilesArgs struct{}

type getC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

type createC2InstanceArgs struct {
	Name        string                 `json:"name" jsonschema:"Name for the C2 profile instance"`
	Description string                 `json:"description,omitempty" jsonschema:"Description of the C2 instance"`
	Parameters  map[string]interface{} `json:"parameters,omitempty" jsonschema:"C2 profile parameters configuration (key-value pairs)"`
	OperationID int                    `json:"operation_id,omitempty" jsonschema:"Operation ID for the C2 instance"`
}

type importC2InstanceArgs struct {
	Name   string `json:"name" jsonschema:"Name for the imported C2 instance"`
	Config string `json:"config" jsonschema:"JSON configuration data to import"`
}

type startC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile to start"`
}

type stopC2ProfileArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile to stop"`
}

type getC2ProfileOutputArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

type c2HostFileArgs struct {
	ProfileID int    `json:"profile_id" jsonschema:"ID of the C2 profile"`
	FileUUID  string `json:"file_uuid" jsonschema:"UUID of the file to host"`
}

type c2SampleMessageArgs struct {
	ProfileID   int    `json:"profile_id" jsonschema:"ID of the C2 profile"`
	MessageType string `json:"message_type" jsonschema:"Type of message (e.g., checkin, get_tasking, post_response)"`
}

type c2GetIOCArgs struct {
	ProfileID int `json:"profile_id" jsonschema:"ID of the C2 profile"`
}

// Tool handlers

// handleGetC2Profiles retrieves all C2 profiles
func (s *Server) handleGetC2Profiles(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfilesArgs) (*mcp.CallToolResult, any, error) {
	profiles, err := s.mythicClient.GetC2Profiles(ctx)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(profiles, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("All C2 profiles (%d total):\n\n%s", len(profiles), string(data)),
			},
		},
	}, wrapList(profiles), nil
}

// handleGetC2Profile retrieves a specific C2 profile by ID
func (s *Server) handleGetC2Profile(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	profile, err := s.mythicClient.GetC2ProfileByID(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	status := "Stopped"
	if profile.Running {
		status = "Running"
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("C2 Profile %d (%s): %s\nType: %s\n\n%s",
					profile.ID, status, profile.Name, profile.Description, string(data)),
			},
		},
	}, profile, nil
}

// handleCreateC2Instance creates a new C2 profile instance
func (s *Server) handleCreateC2Instance(ctx context.Context, req *mcp.CallToolRequest, args createC2InstanceArgs) (*mcp.CallToolResult, any, error) {
	createReq := &types.CreateC2InstanceRequest{
		Name: args.Name,
	}

	// Optional fields
	if args.Description != "" {
		createReq.Description = &args.Description
	}
	if args.Parameters != nil {
		createReq.Parameters = args.Parameters
	}
	if args.OperationID > 0 {
		createReq.OperationID = &args.OperationID
	}

	profile, err := s.mythicClient.CreateC2Instance(ctx, createReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Successfully created C2 instance\nProfile: %s\nID: %d\n\n%s",
					profile.Name, profile.ID, string(data)),
			},
		},
	}, profile, nil
}

// handleImportC2Instance imports a C2 instance from configuration
func (s *Server) handleImportC2Instance(ctx context.Context, req *mcp.CallToolRequest, args importC2InstanceArgs) (*mcp.CallToolResult, any, error) {
	importReq := &types.ImportC2InstanceRequest{
		Name:   args.Name,
		Config: args.Config,
	}

	profile, err := s.mythicClient.ImportC2Instance(ctx, importReq)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Successfully imported C2 instance\nProfile: %s\nID: %d\n\n%s",
					profile.Name, profile.ID, string(data)),
			},
		},
	}, profile, nil
}

// handleStartC2Profile starts a C2 profile
func (s *Server) handleStartC2Profile(ctx context.Context, req *mcp.CallToolRequest, args startC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.StartStopProfile(ctx, args.ProfileID, true)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully started C2 profile %d", args.ProfileID),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"action":     "start",
			"success":    true,
		}, nil
}

// handleStopC2Profile stops a C2 profile
func (s *Server) handleStopC2Profile(ctx context.Context, req *mcp.CallToolRequest, args stopC2ProfileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.StartStopProfile(ctx, args.ProfileID, false)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully stopped C2 profile %d", args.ProfileID),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"action":     "stop",
			"success":    true,
		}, nil
}

// handleGetC2ProfileOutput retrieves C2 profile output
func (s *Server) handleGetC2ProfileOutput(ctx context.Context, req *mcp.CallToolRequest, args getC2ProfileOutputArgs) (*mcp.CallToolResult, any, error) {
	output, err := s.mythicClient.GetProfileOutput(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Output for C2 profile %d:\n\n%s", args.ProfileID, string(data)),
			},
		},
	}, output, nil
}

// handleC2HostFile hosts a file on a C2 profile
func (s *Server) handleC2HostFile(ctx context.Context, req *mcp.CallToolRequest, args c2HostFileArgs) (*mcp.CallToolResult, any, error) {
	err := s.mythicClient.C2HostFile(ctx, args.ProfileID, args.FileUUID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	return &mcp.CallToolResult{
			Content: []mcp.Content{
				&mcp.TextContent{
					Text: fmt.Sprintf("Successfully hosted file %s on C2 profile %d", args.FileUUID, args.ProfileID),
				},
			},
		}, map[string]interface{}{
			"profile_id": args.ProfileID,
			"file_uuid":  args.FileUUID,
			"success":    true,
		}, nil
}

// handleC2SampleMessage retrieves a sample C2 message
func (s *Server) handleC2SampleMessage(ctx context.Context, req *mcp.CallToolRequest, args c2SampleMessageArgs) (*mcp.CallToolResult, any, error) {
	message, err := s.mythicClient.C2SampleMessage(ctx, args.ProfileID, args.MessageType)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(message, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("Sample %s message for C2 profile %d:\n\n%s",
					args.MessageType, args.ProfileID, string(data)),
			},
		},
	}, message, nil
}

// handleC2GetIOC retrieves IOCs from a C2 profile
func (s *Server) handleC2GetIOC(ctx context.Context, req *mcp.CallToolRequest, args c2GetIOCArgs) (*mcp.CallToolResult, any, error) {
	ioc, err := s.mythicClient.C2GetIOC(ctx, args.ProfileID)
	if err != nil {
		return nil, nil, translateError(err)
	}

	data, err := json.MarshalIndent(ioc, "", "  ")
	if err != nil {
		return nil, nil, err
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{
				Text: fmt.Sprintf("IOCs for C2 profile %d:\n\n%s", args.ProfileID, string(data)),
			},
		},
	}, ioc, nil
}
